import { NgbModalOptions } from '@ng-bootstrap/ng-bootstrap';

export const modalOptions: NgbModalOptions = {
  backdrop: 'static',
  keyboard: true,
  centered: true,
  windowClass: 'custom-modal',
};

export const testDataList = [
  {
    id: 102,
    type: 'Condo',
    name: 'Ocean Breeze',
    sharedProperty: true,
    streetAddress: '456 Ocean Drive, Miami Beach, FL',
    sqFt: '950',
    leaseType: 'Monthly',
    expectedRent: 3200,
    negotiable: false,
    priceMode: 'Per Month',
    furnished: false,
    amenitiesIncluded: ['Pool', 'Gym Access', '24/7 Security'],
    title: 'Beachfront 1BR Condo with Pool Access',
    description: `Wake up to the sound of waves in this cozy 1-bedroom condo located just steps from the beach. With 950 sq ft of open space, this unit features a modern kitchen, marble countertops, and direct pool access. Ideal for beach lovers and remote workers.`,
    favourite: false,
    comments: [
      {
        id:1,
        user: 'Carla',
        message: 'Is there guest parking available?',
        timestamp: new Date('2025-08-20T14:15:00'),
      },
    ],
    buildingImage: [
      'https://images.pexels.com/photos/261146/pexels-photo-261146.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    ],
  },
  {
    id: 103,
    type: 'House',
    name: 'Mountain Retreat',
    sharedProperty: false,
    streetAddress: '789 Hilltop Lane, Boulder, CO',
    sqFt: '2000',
    leaseType: 'Annual',
    expectedRent: 4500,
    negotiable: true,
    priceMode: 'Per Month',
    furnished: true,
    amenitiesIncluded: ['Fireplace', 'Garage', 'Garden', 'Deck'],
    title: 'Spacious 3BR House with Mountain Views',
    description: `Escape the city in this beautiful 3-bedroom mountain retreat located in the peaceful hills of Boulder. Features include a fully furnished interior, wrap-around deck, fireplace, and a large backyard. Great for families or those seeking tranquility.`,
    favourite: true,
    comments: [
      {
        id:1,
        user: 'Dave',
        message: 'Can pets be allowed?',
        timestamp: new Date('2025-08-22T11:00:00'),
      },
    ],
    buildingImage: [
      'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    ],
  },
  {
    id: 104,
    type: 'Studio',
    name: 'Urban Nest',
    sharedProperty: true,
    streetAddress: '321 5th Ave, New York, NY',
    sqFt: '450',
    leaseType: 'Short-Term',
    expectedRent: 2100,
    negotiable: true,
    priceMode: 'Per Month',
    furnished: true,
    amenitiesIncluded: ['WiFi', 'Elevator', 'Doorman'],
    title: 'Compact Furnished Studio in Midtown Manhattan',
    description: `Live in the center of it all! This smartly designed studio is ideal for city dwellers who want convenience and style. Featuring a Murphy bed, compact kitchen, and modern bathroom. Just blocks from Times Square and subway lines.`,
    favourite: false,
    comments: [
      {
        id:1,
        user: 'Eve',
        message: 'Is there a minimum lease period?',
        timestamp: new Date('2025-08-23T09:20:00'),
      },
    ],
    buildingImage: [
      'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    ],
  },
  {
    id: 105,
    type: 'Townhouse',
    name: 'Suburban Bliss',
    sharedProperty: false,
    streetAddress: '159 Elm Street, Austin, TX',
    sqFt: '1300',
    leaseType: 'Annual',
    expectedRent: 3000,
    negotiable: false,
    priceMode: 'Per Month',
    furnished: false,
    amenitiesIncluded: ['Garage', 'Backyard', 'Washer/Dryer'],
    title: 'Modern 2BR Townhouse in Quiet Neighborhood',
    description: `Enjoy the best of both worlds — suburban peace and urban access. This 2-bedroom townhouse boasts a private garage, fenced backyard, and modern interiors. Close to tech offices, schools, and shopping centers.`,
    favourite: true,
    comments: [],
    buildingImage: [
      'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    ],
  },
  {
    id: 106,
    type: 'Apartment',
    name: 'City Lights Loft',
    sharedProperty: false,
    streetAddress: '800 Market Street, Seattle, WA',
    sqFt: '1100',
    leaseType: 'Monthly',
    expectedRent: 3400,
    negotiable: true,
    priceMode: 'Per Month',
    furnished: true,
    amenitiesIncluded: ['Smart Home Features', 'Gym Access', 'Rooftop Lounge'],
    title: 'Sleek 2BR Loft with City Skyline Views',
    description: `Experience loft-style living in this beautifully designed 2-bedroom unit featuring exposed brick walls, high ceilings, and floor-to-ceiling windows. Located in a vibrant downtown neighborhood with cafes, nightlife, and public transport at your doorstep.`,
    favourite: false,
    comments: [
      {
        id:1,
        user: 'Frank',
        message: 'Does it come with parking?',
        timestamp: new Date('2025-08-21T16:45:00'),
      },
    ],
    buildingImage: [
      'https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    ],
  },
  {
    id: 107,
    type: 'Penthouse',
    name: 'Skyline Heights',
    sharedProperty: false,
    streetAddress: '1010 Sunset Blvd, Los Angeles, CA',
    sqFt: '2200',
    leaseType: 'Annual',
    expectedRent: 8500,
    negotiable: true,
    priceMode: 'Per Month',
    furnished: true,
    amenitiesIncluded: ['Infinity Pool', 'Private Elevator', 'Smart Home Features', 'Gym Access'],
    title: 'Luxury 3BR Penthouse Overlooking Downtown LA',
    description: `Live in unmatched luxury in this stunning penthouse perched high above Los Angeles. This 3-bedroom, 3.5-bathroom residence spans over 2200 sq ft and features wrap-around floor-to-ceiling windows that deliver breathtaking panoramic views of the city skyline and beyond.The open-concept living and dining areas are ideal for both entertaining and relaxing. A chef-grade kitchen includes professional-grade appliances, marble countertops, and a large center island. Each bedroom has its own ensuite bathroom and balcony access.The master suite is a private retreat featuring a walk-in closet, spa-inspired bathroom with a soaking tub and steam shower, and direct access to a private terrace. Additional amenities include smart climate control, a fully automated lighting system, a secure underground garage, and access to a rooftop pool and private fitness club.Located minutes from Hollywood, Rodeo Drive, and Sunset Strip, this property is perfect for executives, entertainers, or those seeking prestige and privacy.`,
    favourite: true,
    comments: [],
    buildingImage: ['https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg'],
  },
  {
    id: 108,
    type: 'Villa',
    name: 'Coastal Haven',
    sharedProperty: false,
    streetAddress: '500 Seaview Drive, Malibu, CA',
    sqFt: '3500',
    leaseType: 'Short-Term',
    expectedRent: 12000,
    negotiable: false,
    priceMode: 'Per Week',
    furnished: true,
    amenitiesIncluded: ['Private Beach Access', 'Outdoor Kitchen', 'Firepit', 'Infinity Pool'],
    title: 'Exclusive Oceanfront Villa with Private Beach',
    description: `Experience the ultimate in oceanfront living in this Malibu villa that defines coastal elegance. Sprawled across 3500 sq ft of high-end design, this 4-bedroom, 5-bathroom estate offers direct access to a private beach, panoramic views of the Pacific Ocean, and resort-style living.Designed with a seamless blend of indoor and outdoor spaces, this villa features an expansive living room with retractable glass walls that open to an oceanfront patio with a heated infinity pool, outdoor dining, a fully equipped chef’s BBQ station, and a custom firepit.Each suite includes a luxury ensuite bath, with the master boasting a private deck and soaking tub with views of the sea. This property also features a state-of-the-art media room, an office, and a meditation garden.Perfect for short-term luxury getaways, film industry rentals, or retreats. Concierge services, private chefs, and daily housekeeping are available on request.`,
    favourite: true,
    comments: [
      {
        id:1,
        user: 'Sophia',
        message: 'Is this available for a 2-week rental in December?',
        timestamp: new Date('2025-08-25T12:30:00'),
      },
    ],
    buildingImage: [
      'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg',
      'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg',
      'https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg',
      'https://images.pexels.com/photos/271619/pexels-photo-271619.jpeg',
    ],
  },
  {
    id: 109,
    type: 'Loft',
    name: 'Brick & Beam',
    sharedProperty: true,
    streetAddress: '77 King Street, Boston, MA',
    sqFt: '1400',
    leaseType: 'Annual',
    expectedRent: 4100,
    negotiable: true,
    priceMode: 'Per Month',
    furnished: false,
    amenitiesIncluded: ['Exposed Brick', 'Washer/Dryer', 'Walk-in Closet'],
    title: 'Historic 2BR Loft in Downtown Boston',
    description: `Nestled in the heart of Boston’s historic district, this beautiful loft apartment offers an iconic mix of heritage and modern amenities. The space features original exposed brick walls, high wood-beam ceilings, large warehouse-style windows, and newly refinished hardwood flooring.The kitchen boasts modern stainless-steel appliances, quartz countertops, and open shelving, while the expansive living room provides plenty of space for work and relaxation. Bedrooms are bright and spacious, with walk-in closets and architectural charm throughout.Ideal for professionals, creatives, or academics, the loft is within walking distance to downtown Boston, multiple universities, and major transit lines. The building also includes secure entry, bike storage, and optional basement parking.Enjoy city life while living in a piece of history.`,
    favourite: false,
    comments: [
      {
        id:1,
        user: 'Liam',
        message: 'Is a parking spot included in the lease?',
        timestamp: new Date('2025-08-24T08:00:00'),
      },
      {
        id:2,
        user: 'Alice',
        message: 'Is this property still available?',
        timestamp: new Date('2025-08-24T10:30:00'),
      },
      {
        id:3,
        user: 'Bob',
        message: 'Can I schedule a visit this weekend?',
        timestamp: new Date('2025-08-25T15:45:00'),
      },
    ],
    buildingImage: [
      'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg',
      'https://images.pexels.com/photos/271743/pexels-photo-271743.jpeg',
      'https://images.pexels.com/photos/276528/pexels-photo-276528.jpeg',
    ],
  },
];

export const test = {
  id: 101,
  type: 'Apartment',
  name: 'Sunset View',
  sharedProperty: false,
  streetAddress: '123 Main Street, San Francisco, CA',
  sqFt: '850',
  leaseType: 'Annual',
  expectedRent: 2800,
  negotiable: true,
  priceMode: 'Per Month',
  furnished: true,
  amenitiesIncluded: ['WiFi', 'Air Conditioning', 'Washer/Dryer', 'Gym Access'],
  title: 'Modern 2BR Apartment with Great View',
  description: `Welcome to your dream apartment in the heart of San Francisco. This stunning 2-bedroom, 1.5-bathroom unit offers a perfect blend of modern living and classic charm. With over 850 square feet of thoughtfully designed space, the apartment features large windows that flood the rooms with natural light, hardwood flooring throughout, and high ceilings that create a spacious atmosphere.The open-concept kitchen is equipped with stainless steel appliances, granite countertops, and ample cabinet space, making it ideal for cooking and entertaining. The living room opens up to a private balcony with panoramic views of the city and bay — perfect for morning coffee or evening relaxation.Both bedrooms are generously sized with built-in wardrobes and share access to a luxurious bathroom complete with a soaking tub and rainfall shower. Additional features include in-unit washer and dryer, high-speed internet, central air conditioning, and keyless smart entry.Residents also have access to a shared fitness center, secure underground parking, and a rooftop terrace with grilling stations and lounge seating. Located just steps from local cafes, grocery stores, public transportation, and Golden Gate Park, this apartment offers unmatched convenience and lifestyle.Whether you're a young professional, a couple, or a small family, this property is a rare opportunity to live in one of the city's most desirable neighborhoods. Schedule your tour today and experience urban living at its finest.`,
  favourite: true,
  comments: [
    {
      id:1,
      user: 'Alice',
      message: 'Is this property still available?',
      timestamp: new Date('2025-08-24T10:30:00'),
    },
    {
      id:2,
      user: 'Bob',
      message: 'Can I schedule a visit this weekend?',
      timestamp: new Date('2025-08-25T15:45:00'),
    },
  ],
  buildingImage: ['https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'],
};

export const amenities = [
  'Gym/Fitness Center',
  'Swimming Pool',
  'Car Park',
  'Visitors Parking',
  'Power Backup',
  'Garbage Disposal',
  'Private Lawn',
  'Water Heater',
  'Plant Security System',
  'Laundry Service',
  'Elevator',
  'Club House',
];

export const AuthorizationInfo = [
  {
    email: 'John.doe@gmail.com',
    password: '87654321',
  },
  {
    email: 'Dave.victor@gmail.com',
    password: 'daveVictor',
  },
];
